from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect

# Create your views here.
def user_login(request):
    """
    Render the login page for user authentication.

    Args:
        request (HttpRequest): The HTTP request object generated by the client.

    Returns:
        HttpResponse: The rendered HTML template as an HTTP response.

    Raises:
        None

    Example usage:
        >>> request = HttpRequest()
        >>> user_login(request)
        <HttpResponse object at 0x00000123ABCDEF>
    """
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    """
    Authenticate a user based on the provided login credentials.

    Args:
        request (HttpRequest): The HTTP request object generated by the client.

    Returns:
        HttpResponse: Redirects to the home page if authentication is successful.
        HttpResponse: Renders the login page with an error message if authentication fails.

    Raises:
        None

    Example usage:
        This function is typically called when the user submits the login form.
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('homepage') # replace with the URL name of your home page
    else:
        login(request, user)
        error_message = "Invalid login credentials. Please try again."
        return render(request, 'login.html', {'error_message': error_message})