from django.shortcuts import render

# Create your views here.
def home(request):
    """
    Render the home page of the website.

    Args:
        request (HttpRequest): The HTTP request object generated by the client.

    Returns:
        HttpResponse: The rendered HTML template as an HTTP response.

    Raises:
        None

    Example usage:
        >>> request = HttpRequest()
        >>> home(request)
        <HttpResponse object at 0x00000123ABCDEF>
    """
    return render(request, "home.html")
